#! /bin/sh

# start the hotkey daemon
sxhkd &

# setup virtual desktops (on the focused monitor)
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width	8
bspc config window_gap		40

bspc config click_to_focus	true
bspc config gapless_monocle	true

# per application rules
bspc rule -a Emacs state=tiled
